"""added some columns

Revision ID: a6d74da275bb
Revises: 5133bca710b3
Create Date: 2024-10-04 08:26:28.188245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d74da275bb'
down_revision = '5133bca710b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('drop_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('drop_name')
        batch_op.drop_column('pickup_name')

    # ### end Alembic commands ###
